version: "3.0"
services:
  db:
    container_name: db
    image: postgres:13.4
    user: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    image: newhorizontech/simplecrud
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ror-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
