name: Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "crud-my-notes"
          heroku_email: "alaukikinbox@gmail.com"
          buildpack: "https://github.com/heroku/heroku-buildpack-ruby.git"
